// Generated by gencpp from file tutorial/multiplier.msg
// DO NOT EDIT!


#ifndef TUTORIAL_MESSAGE_MULTIPLIER_H
#define TUTORIAL_MESSAGE_MULTIPLIER_H

#include <ros/service_traits.h>


#include <tutorial/multiplierRequest.h>
#include <tutorial/multiplierResponse.h>


namespace tutorial
{

struct multiplier
{

typedef multiplierRequest Request;
typedef multiplierResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct multiplier
} // namespace tutorial


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tutorial::multiplier > {
  static const char* value()
  {
    return "a7d7d7065d45755acef7d4dcf908162a";
  }

  static const char* value(const ::tutorial::multiplier&) { return value(); }
};

template<>
struct DataType< ::tutorial::multiplier > {
  static const char* value()
  {
    return "tutorial/multiplier";
  }

  static const char* value(const ::tutorial::multiplier&) { return value(); }
};


// service_traits::MD5Sum< ::tutorial::multiplierRequest> should match
// service_traits::MD5Sum< ::tutorial::multiplier >
template<>
struct MD5Sum< ::tutorial::multiplierRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tutorial::multiplier >::value();
  }
  static const char* value(const ::tutorial::multiplierRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tutorial::multiplierRequest> should match
// service_traits::DataType< ::tutorial::multiplier >
template<>
struct DataType< ::tutorial::multiplierRequest>
{
  static const char* value()
  {
    return DataType< ::tutorial::multiplier >::value();
  }
  static const char* value(const ::tutorial::multiplierRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tutorial::multiplierResponse> should match
// service_traits::MD5Sum< ::tutorial::multiplier >
template<>
struct MD5Sum< ::tutorial::multiplierResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tutorial::multiplier >::value();
  }
  static const char* value(const ::tutorial::multiplierResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tutorial::multiplierResponse> should match
// service_traits::DataType< ::tutorial::multiplier >
template<>
struct DataType< ::tutorial::multiplierResponse>
{
  static const char* value()
  {
    return DataType< ::tutorial::multiplier >::value();
  }
  static const char* value(const ::tutorial::multiplierResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUTORIAL_MESSAGE_MULTIPLIER_H
